<?php

        try {
      
                echo "[{\"USERNAME\":\"saran.puangsuk@roche.com\",\"CURRENT_YEAR\":\"2020\",\"PREVIOUS_YEAR\":\"2019\",\"CURRENT_CYCLE\":\"1\",\"CURRENT_QUARTER\":\"N\/A\",\"PREVIOUS_QUARTER\":\"N\/A\",\"CURRENT_MONTH\":\"2\",\"PREVIOUS_MONTH\":\"N\/A\",\"CURRENT_SALES_AREA\":\"GS\",\"BRAND\":\"RECORMON\",\"CYCLE_CURRENT_SALES\":\"3246840\",\"CYCLE_PREVIOUS_SALES\":\"3042666\",\"CYCLE_SALES_GROWTH\":\"204174\",\"CYCLE_GROWTH_PERCENTAGE\":\"6.7%\",\"YTD_CURRENT_SALES\":\"3246840\",\"YTD_PREVIOUS_SALES\":\"3042666\",\"YTD_SALES_GROWTH\":\"204174\",\"YTD_GROWTH_PERCENTAGE\":\"6.7%\",\"YOY_CURRENT_SALES\":\"1211526\",\"YOY_PREVIOUS_SALES\":\"1653696\",\"YOY_SALES_GROWTH\":\"-442170\",\"YOY_GROWTH_PERCENTAGE\":\"-26.7%\",\"QTD_PREVIOUS_YEAR_CURRENT_SALES\":\"0\",\"QTD_PREVIOUS_YEAR_PREVIOUS_SALES\":\"0\",\"QTD_PREVIOUS_YEAR_SALES_GROWTH\":\"0\",\"QTD_PREVIOUS_YEAR_GROWTH_PERCENTAGE\":\"0\",\"QTD_PREVIOUS_QUARTER_CURRENT_SALES\":\"0\",\"QTD_PREVIOUS_QUARTER_PREVIOUS_SALES\":\"0\",\"QTD_PREVIOUS_QUARTER_SALES_GROWTH\":\"0\",\"QTD_PREVIOUS_QUARTER_GROWTH_PERCENTAGE\":\"0\",\"MTD_CURRENT_SALES\":\"0\",\"MTD_PREVIOUS_SALES\":\"0\",\"MTD_SALES_GROWTH\":\"0\",\"MTD_GROWTH_PERCENTAGE\":\"0\",\"LAST_UPDATED_DATE\":\"feb-17-2020 00:00:00\",\"COUNTRY\":\"TH\",\"NAME\":\"Saran Puangsuk\",\"TERRITORY_NAME\":\"GS\"}]";
     
        } catch (Exception $e) {
            echo 'Caught exception: ',  $e->getMessage(), "\n";
        }

   
?>